name: Probe1

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]
        include:
          - os: macOS-latest

    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p foo/bar; cd foo/bar
      - run: pwd
