name: Probe1

on: [push, workflow_dispatch]

env:
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  node_version: "22.7.0"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-13]
        include:
          - os: macOS-13

    steps:
      - name: Install MacPorts and clang
        run:
          aria2c "https://github.com/macports/macports-base/releases/download/v2.10.1/MacPorts-2.10.1-13-Ventura.pkg"
          
          sudo installer -pkg MacPorts-2.10.1-13-Ventura.pkg -target /

          export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

          sudo port install clang-11 clang-14

          sudo port destroot macports-libcxx

          sudo port install macports-libcxx
          
          sudo port select --set clang mp-clang-14

          curl -L --compressed "https://github.com/llvm/llvm-project/raw/release/11.x/libcxxabi/include/cxxabi.h" -o cxxabi.h

          curl -L --compressed "https://github.com/llvm/llvm-project/raw/release/11.x/libcxxabi/include/__cxxabi_config.h" -o __cxxabi_config.h

          sudo mv -f cxxabi.h /opt/local/include/libcxx/v1/cxxabi.h

          sudo mv -f __cxxabi_config.h /opt/local/include/libcxx/v1/__cxxabi_config.h

      - name: Get source and build
        run:
          initial=$(pwd)

          curl -L "https://github.com/nodejs/node/archive/refs/tags/v${{ env.node_version }}.tar.gz" | tar -x

          cd "node-${{ env.node_version }}"

          sed -i '' "s/'11.0'/'${{ env.MACOSX_DEPLOYMENT_TARGET }}'/" common.gypi

          sed -i '' -e 's/std::u8string/std::filesystem::path/' -e 's|(compile_cache_dir_ / Uint32ToHex(key)).u8string();|compile_cache_dir_ / Uint32ToHex(key);|' -e 's|std::string(cache_filename_u8.begin(), cache_filename_u8.end())|cache_filename_u8|' -e '/cache_dir_with_tag_u8/d' -e 's/cache_dir_with_tag_str/cache_dir_with_tag/' -e 's/cache_filename_u8/cache_filename_str/' src/compile_cache.cc

          export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

          export CPPFLAGS="-nostdinc++ -isystem/opt/local/include/libcxx/v1 -D_LIBCPP_DISABLE_AVAILABILITY"

          export LDFLAGS="-nostdlib++ -L/opt/local/lib/libcxx -Wl,-rpath,/opt/local/lib/libcxx -lc++"

          ./configure

          make -j4

          rm -r out/Release/obj.target

          rm out/Release/libv8_base_without_compiler.a; rm out/Release/libv8_initializers.a; rm out/Release/libv8_compiler.a; rm out/Release/libnode.a; rm out/Release/libv8_turboshaft.a

          tar -c --zstd -f $initial/node.tar.zst out/Release

      - name: Upload SDK artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-${{ env.node_version }}
          path: node.tar.zst
