name: Probe1

on: [push, workflow_dispatch]

env:
  MACOSX_DEPLOYMENT_TARGET: "10.13"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]
        include:
          - os: macOS-latest

    steps:
      - uses: actions/checkout@v3
      - run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git;
          export PATH="$PATH:$PWD/depot_tools";

          mkdir dart-sdk; cd dart-sdk; fetch --no-history dart;
          cd sdk;

          git reset --hard 3.1.0;

          sed -i '' 's/"10.14"/"10.13"/' build/config/mac/mac_sdk.gni;
          sed -i '' -E 's/(#pragma clang diagnostic push|#pragma clang diagnostic ignored "-Wdeprecated"|#pragma clang diagnostic pop)//' runtime/bin/security_context_macos.cc;

          cat build/config/mac/mac_sdk.gni runtime/bin/security_context_macos.cc;

# stable tag: 3.1.0
