name: Probe2

on: [push, workflow_dispatch]

env:
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  api_accept: 'Accept: application/vnd.github.v3+json'
  api_ver: 'X-GitHub-Api-Version: 2022-11-28'
  rel_filter: first( .[] | select(.prerelease != true) | select(.draft != true) | select(.tag_name | startswith("cli/")) )

jobs:

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            code-target: darwin-x64

    steps:
      # Github docs say jq is installed in the runner image, but wherever it is, it isn't in the PATH https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#utilities
      - name: Install jq
        uses: dcarbone/install-jq-action@v1.0.1

      - name: Get source of latest stable CLI release
        run:
          curl --compressed -L -H "${{ env.api_accept }}" -H "${{ env.api_ver }}" 'https://api.github.com/repos/biomejs/biome/releases' | jq '${{ env.rel_filter }}' > rel.json

          TARBALL=$(cat rel.json | jq -r '.tarball_url')

          mkdir biome && cd biome

          curl -L $TARBALL | tar --strip-components=1 -x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust toolchain
        run: rustup target add ${{ matrix.target }}

      - name: Build from source
        run:
          export BIOME_VERSION=$(cat rel.json | jq -r '.tag_name' | sed 's/^cli\/v//')

          cd biome

          cargo build -p biome_cli --release --target ${{ matrix.target }}

          mv target/${{ matrix.target }}/release/biome biome

        env:
          RUSTFLAGS: "-C strip=symbols"

      - name: Upload cli artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli
          path: biome/biome
