name: Probe1

on: [push, workflow_dispatch]

env:
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  node_version: "22.7.0"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-13]
        include:
          - os: macOS-13

    # try to use clang-14 built for hs - if that fails, try to at least have the libs as built for hs
    steps:
      - name: Install MacPorts and clang
        run:
          export _clang_pkg="clang-14-14.0.6_2+analyzer.darwin_17.x86_64"
          
          aria2c "https://packages.macports.org/clang-14/$_clang_pkg.tbz2"

          mkdir -p $_clang_pkg

          tar -xf $_clang_pkg.tbz2 -C $_clang_pkg

          aria2c "https://github.com/macports/macports-base/releases/download/v2.10.1/MacPorts-2.10.1-13-Ventura.pkg"
          
          sudo installer -pkg MacPorts-2.10.1-13-Ventura.pkg -target /

          export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

          sudo port install clang-14

          sudo rsync -v --ignore-times $_clang_pkg/ /
          
          sudo port select --set clang mp-clang-14

          rm -f MacPorts-2.10.1-13-Ventura.pkg $_clang_pkg.tbz2

      - name: Get source and build
        run:
          initial=$(pwd)

          curl -L "https://github.com/nodejs/node/archive/refs/tags/v${{ env.node_version }}.tar.gz" | tar -x

          cd "node-${{ env.node_version }}"

          sed -i '' "s/'11.0'/'${{ env.MACOSX_DEPLOYMENT_TARGET }}'/" common.gypi

          export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

          export CPPFLAGS="-nostdinc++ -isystem/opt/local/libexec/llvm-14/include/c++/v1 -D_LIBCPP_DISABLE_AVAILABILITY"

          export LDFLAGS="-nostdlib++ -L/opt/local/libexec/llvm-14/lib -Wl,-rpath,/opt/local/libexec/llvm-14/lib -lc++"

          ./configure

          make -j4

          rm -r out/Release/obj.target

          rm out/Release/libv8_base_without_compiler.a; rm out/Release/libv8_initializers.a; rm out/Release/libv8_compiler.a; rm out/Release/libnode.a; rm out/Release/libv8_turboshaft.a

          tar -c --zstd -f $initial/node.tar.zst out/Release

      - name: Upload SDK artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-${{ env.node_version }}
          path: node.tar.zst
