name: Probe4

on: [push, workflow_dispatch]

env:
  artifact_name: sdk-3.3.3
  run_id: 8471303268
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]
        include:
          - os: macOS-latest

    steps:
      - name: Download Dart artifact
        run:
          git clone https://github.com/cristianl/throwaway1

          cd throwaway1

          gh run download $run_id

          ls -al $artifact_name
