name: Probe1

on: [push, workflow_dispatch]

env:
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  dart_version: "3.2.0"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]
        include:
          - os: macOS-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get source of latest stable release
        run:
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git;
          export PATH="$PATH:$PWD/depot_tools";

          mkdir dart-sdk; cd dart-sdk; fetch dart;
          cd sdk;

          git reset --hard $dart_version;
          gclient sync;

      - name: Build from source
        run:
          cd dart-sdk/sdk;
          sed -i '' 's/"10.14"/"10.13"/' build/config/mac/mac_sdk.gni;
          sed -i '' -E 's/(#pragma clang diagnostic push|#pragma clang diagnostic ignored "-Wdeprecated"|#pragma clang diagnostic pop)//' runtime/bin/security_context_macos.cc;

          ./tools/build.py --no-goma --mode release --arch x64 create_sdk;

          tar -c --zstd -f sdk.tar.zst xcodebuild/ReleaseX64/dart-sdk;

      - name: Upload SDK artifact
        uses: actions/upload-artifact@v3
        with:
          name: sdk
          path: dart-sdk/sdk/sdk.tar.zst
