name: Probe1

on: [push, workflow_dispatch]

env:
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  dart_version: "3.2.1"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]
        include:
          - os: macOS-latest

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Get source of release version ${{ env.dart_version }}
        run:
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

          export PATH="$PATH:$PWD/depot_tools"

          mkdir dart-sdk && cd dart-sdk

          fetch dart

          cd sdk

          git reset --hard $dart_version

          gclient sync

      - name: Build from source
        run:
          initial=$(pwd)

          cd dart-sdk/sdk

          sed -i '' 's/"10.14"/"10.13"/' build/config/mac/mac_sdk.gni

          sed -i '' -E 's/(#pragma clang diagnostic push|#pragma clang diagnostic ignored "-Wdeprecated"|#pragma clang diagnostic pop)//' runtime/bin/security_context_macos.cc

          ./tools/build.py --no-goma --mode release --arch x64 create_sdk

          cd xcodebuild/ReleaseX64

          tar -c --zstd -f $initial/sdk.tar.zst dart-sdk

      - name: Upload SDK artifact
        uses: actions/upload-artifact@v3
        with:
          name: sdk-${{ env.dart_version }}
          path: sdk.tar.zst
