name: Probe1

on: [push, workflow_dispatch]

env:
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  node_version: "22.7.0"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-13]
        include:
          - os: macOS-13

    steps:
      - name: Install MacPorts and clang
        run:
          aria2c "https://github.com/macports/macports-base/releases/download/v2.10.1/MacPorts-2.10.1-13-Ventura.pkg"
          
          sudo sudo installer -pkg MacPorts-2.10.1-13-Ventura.pkg -target /

          sudo echo "macosx_deployment_target  10.13" >> /opt/local/etc/macports/macports.conf
          
          sudo port install clang-14 macports-libcxx
          
          sudo port select --set clang mp-clang-14

      - name: Get source and build
        run:
          initial=$(pwd)

          curl -L "https://github.com/nodejs/node/archive/refs/tags/v${{ env.node_version }}.tar.gz" | tar -x

          cd "node-${{ env.node_version }}"

          sed -i '' "s/'11.0'/'${{ env.MACOSX_DEPLOYMENT_TARGET }}'/" common.gypi

          export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

          export CPPFLAGS="-isystem/opt/local/include/libcxx/v1 -D_LIBCPP_DISABLE_AVAILABILITY -nostdinc++ -nostdlib++ -lc++"

          export LDFLAGS="-L/opt/local/lib/libcxx -Wl,-rpath,/opt/local/lib/libcxx"

          ./configure

          rm -r out/Release/obj.target

          rm out/Release/libv8_base_without_compiler.a; rm out/Release/libv8_initializers.a; rm out/Release/libv8_compiler.a; rm out/Release/libnode.a; rm out/Release/libv8_turboshaft.a

          tar -c --zstd -f $initial/node.tar.zst out/Release

      - name: Upload SDK artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-${{ env.node_version }}
          path: node.tar.zst
