name: Probe1

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]
        include:
          - os: macOS-latest

    steps:
      - uses: actions/checkout@v3
      - run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git; export PATH="$PATH:$PWD/depot_tools";   mkdir dart-sdk; cd dart-sdk; fetch dart;   cd sdk;
      - run: ls /Users/runner/work/throwaway1/throwaway1/dart-sdk; ls /Users/runner/work/throwaway1/throwaway1/dart-sdk/sdk
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: sdk-1
      #     path: /Users/runner/work/throwaway1/throwaway1/dart-sdk/sdk.tar.zst
