name: Probe1

on: [push, workflow_dispatch]

env:
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  node_version: "22.7.0"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-13]
        include:
          - os: macOS-13

    steps:
      - name: Get source and build
        run:
          initial=$(pwd)

          curl -L "https://github.com/nodejs/node/archive/refs/tags/v${{ env.node_version }}.tar.gz" | tar -x

          brew install llvm@12

          cd "node-${{ env.node_version }}"

          sed -i '' "s/'11.0'/'${{ env.MACOSX_DEPLOYMENT_TARGET }}'/" common.gypi

          export LDFLAGS="-L$HOMEBREW_PREFIX/opt/llvm@12/lib -Wl,-rpath,$HOMEBREW_PREFIX/opt/llvm@12/lib"

          ./configure

          make -j4

          rm -r out/Release/obj.target

          rm out/Release/libv8_base_without_compiler.a; rm out/Release/libv8_initializers.a; rm out/Release/libv8_compiler.a; rm out/Release/libnode.a; rm out/Release/libv8_turboshaft.a

          tar -c --zstd -f $initial/node.tar.zst out/Release

      - name: Upload SDK artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-${{ env.node_version }}
          path: node.tar.zst
