name: Probe1

on: [push, workflow_dispatch]

env:
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  node_version: "22.7.0"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-13]
        include:
          - os: macOS-13

    steps:
      # - uses: actions/checkout@v4
      #   with:
      #     ref: 'probe1'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Get source and build
        run:
          initial=$(pwd)

          curl -L "https://github.com/nodejs/node/archive/refs/tags/v${{ env.node_version }}.tar.gz" | tar -x

          cd "node-${{ env.node_version }}"

          sed -i '' "s/'11.0'/'${{ env.MACOSX_DEPLOYMENT_TARGET }}'/" common.gypi

          ./configure

          make -j4

          cd out

          tar -c --zstd -f $initial/node.tar.zst Release

      - name: Upload SDK artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-${{ env.node_version }}
          path: node.tar.zst
